### ISSUE TITLE
universe.getType returns undefined values

### ISSUE THREAD

**Issue by EMQcarlos** [lhkbob/eve-swagger-js#10]
When calling ESI.universe.getType with an id it returns the correct group_id and icon_id, however all other, non number, values are returned as undefined.

`ESI.universe.getType(3329, ac).then(function (type) {
  console.log(type);
}).catch(function (error) {
  console.error(error);
});`

returns:

> exports {
>   category_id: undefined,
>   group_id: 257,
>   type_description: undefined,
>   type_name: undefined,
>   icon_id: 33 }

**Comment by lhkbob** [comment]
It looks like a new release of ESI has changed the universe/types/id end point and changed some property names.  They dropped graphic_id and removed the 'type_' prefix for the name and description fields.

This will just require regenerating the back-end code from swagger, which I can do this weekend. Thanks for the report

**Comment by lhkbob** [comment]
Should be fixed if you update to use the 0.1.3 tag for your dependency.
