### ISSUE TITLE
index of error.

### ISSUE THREAD

**Issue by janat08** [lhkbob/eve-swagger-js#37]
For this:
```
      esi.corporations(1).info().then(result => {
  console.log(result);
}).catch(error => {
  console.error(error);
});
```
I get this:

```
modules.js?hash=c2f08ee…:118450 Unhandled rejection esi:Error: Error contacting ESI service for https://esi.tech.ccp.is/v4/characters/1/: Cannot read property 'indexOf' of undefined
    at getExceptionFromAgentError (http://localhost:3000/packages/modules.js?hash=c2f08eef8e8d7f965119d7e48560ac92e2151e66:97349:17)
    at http://localhost:3000/packages/modules.js?hash=c2f08eef8e8d7f965119d7e48560ac92e2151e66:97504:22
    at Request.callback (http://localhost:3000/packages/modules.js?hash=c2f08eef8e8d7f965119d7e48560ac92e2151e66:107906:12)
    at Request.end (http://localhost:3000/packages/modules.js?hash=c2f08eef8e8d7f965119d7e48560ac92e2151e66:107975:17)
    at http://localhost:3000/packages/modules.js?hash=c2f08eef8e8d7f965119d7e48560ac92e2151e66:97500:19
    at http://localhost:3000/packages/modules.js?hash=c2f08eef8e8d7f965119d7e48560ac92e2151e66:97499:16
From previous event:
    at ESIRequestHandler._request (http://localhost:3000/packages/modules.js?hash=c2f08eef8e8d7f965119d7e48560ac92e2151e66:97480:25)
    at Object.<anonymous> (http://localhost:3000/packages/modules.js?hash=c2f08eef8e8d7f965119d7e48560ac92e2151e66:97446:26)
    at Object.wrapped (http://localhost:3000/packages/modules.js?hash=c2f08eef8e8d7f965119d7e48560ac92e2151e66:116610:22)
    at http://localhost:3000/packages/modules.js?hash=c2f08eef8e8d7f965119d7e48560ac92e2151e66:116550:34
```

**Comment by lhkbob** [comment]
Hi Janat, thanks for the bug report but I'm struggling to reproduce this error from the snippet you've posted. If I run it as-is I get the expected exception that a corporation with id = 1 doesn't exist. If I use a valid corporation id, the request completes successfully.

From your stack trace it looks like all of your modules are hosted through something else that I'm not familiar with. Does this also transform the code? In both the ES6 and babel-generated code, there is no indexOf use in the esi-agent.js file at all (which holds the ESIRequestHandler class definition).

If you could send me more info that would be very helpful. One thing to test would be does the corporations().info() function work correctly with a good id? Also, looking at the stack trace, it refers to the characters route, were you actually testing `esi.characters(1).info()`?

**Comment by janat08** [comment]
Oh lol, yes. 1 does not make an id. this stack trace is virtual dom of vue.js for you :D which runs on meteor.js. I ran characters().info with valid id, and get same error irregardless of what endpoint I try access. I find that this works though: https://github.com/swagger-api/swagger-js. If i try and access eve api somewhat manually (like stab in the dark sort of thing) with http package then I get complaints about cors and headers and stuff.

**Comment by lhkbob** [comment]
Okay, so this was running in a browser environment then. I'm betting the babel settings aren't set up for that (it targets Node v4 at the moment). I will look into it and hopefully will have it fixed for the next release.

**Comment by lhkbob** [comment]
It would be helpful if you could send me the modules.js file that was built so I can figure out what part of my original code is producing this issue.

**Comment by janat08** [comment]
meteor.js is fairly futuristic (as in it has babel), and it runs on node 4.
There is no top level modules.js file and I couldn't find one in npm
package directory.

**Comment by lhkbob** [comment]
I think the module.js is a generated file that is served to the browser (assuming that this error comes from code for your front-end running in the browser).  If you debug via the browser you should be able to see the content of that file and copy it from there.

**Comment by janat08** [comment]
It rarely actually points at actual source code. I didn't find common.js.

[modules.zip](https://github.com/lhkbob/eve-swagger-js/files/1070740/modules.zip)

**Comment by janat08** [comment]
@lhkbob updated error coming...

**Comment by janat08** [comment]
```
(anonymous)	@	corporateHome.vue:104
tryCatcher	@	modules.js?hash=fb52fa6…:122125
Promise._settlePromiseFromHandler	@	modules.js?hash=fb52fa6…:120148
Promise._settlePromise	@	modules.js?hash=fb52fa6…:120205
Promise._settlePromise0	@	modules.js?hash=fb52fa6…:120250
Promise._settlePromises	@	modules.js?hash=fb52fa6…:120325
(anonymous)	@	modules.js?hash=fb52fa6…:117085
(anonymous)	@	meteor.js:1105
```

**Comment by janat08** [comment]
my laptop crashed in between, and the promise stuff isn't related.

**Comment by lhkbob** [comment]
I have been unable to reproduce this in my own environment with Vue in the browser.  However, the only thing I wasn't able to configure in my tests was using meteor. Hypothetically this could be a source of the problem.

At this point, though, I am not quite seeing what I'd expect in your stack traces.  With the first stack trace, the language "unhandled rejection" means that you don't have a catch() clause in the appropriate place.  If you properly catch it you should be able to print out the full stack trace of the original cause (the stack trace provided just provides the expected stack for wrapping the seed cause `Cannot read property 'indexOf' of undefined`).  You may also wish to make sure your meteor build and browser support source maps, which will help debug things further.

When I catch a failed request from the esi library in Vue, I get an exception like:
```
VError {
  name: "esi:NotFoundError",
  jse_shortmsg: "Error from ESI service for https://esi.tech.ccp.is…ters/XYZ/: {"error": "Character not found"}", 
   jse_cause: Error: cannot GET https://esi.tech.ccp.is/v4/characters/XYZ/?datasource=tranquility&language=e…, 
   message: "Error from ESI service for https://esi.tech.ccp.is…/?datasource=tranquility&language=en-us (404)"… } 
  stack:
    at Response.toError (eval at <anonymous> (http://localhost:8081/dist/build.js:3985:1), <anonymous>:466:13)
    at Response.setStatusProperties (eval at <anonymous> (http://localhost:8081/dist/build.js:3985:1), <anonymous>:440:12)
    at new Response (eval at <anonymous> (http://localhost:8081/dist/build.js:3985:1), <anonymous>:334:8)
    at Request.eval (eval at <anonymous> (http://localhost:8081/dist/build.js:3985:1), <anonymous>:500:13)
    at Request.Emitter.emit (eval at <anonymous> (http://localhost:8081/dist/build.js:2909:1), <anonymous>:133:20)
    at XMLHttpRequest.xhr.onreadystatechange (eval at <anonymous> (http://localhost:8081/dist/build.js:3985:1), <anonymous>:886:10)
   ... etc.
(anonymous) @ CronLog.vue?e556:118
tryCatcher @ bluebird.js?e366:5253
Promise._settlePromiseFromHandler @ bluebird.js?e366:3275
Promise._settlePromise @ bluebird.js?e366:3332
Promise._settlePromise0 @ bluebird.js?e366:3377
Promise._settlePromises @ bluebird.js?e366:3452
(anonymous) @ bluebird.js?e366:175
```
The major difference between this and the second stack trace you've posted is the details about the VError instance, including the cause data.  This cause for you should indicate what actual piece of code was failing to find an `indexOf` property. 


If you're not able to figure this out, but can provide a simple test case with a package.json and build script that goes through meteor, etc. I will work through it further.
